version: 2

sources:
  - name: raw
    description: "Raw Parquet files from ingestion layer"
    meta:
      owner: "Kliti Hamataj"

    tables:
      - name: irceline
        description: "IRCELINE SOS API measurements"
        meta:
          source_url: "https://geo.irceline.be/sos/api/v1/"
          update_frequency: "hourly"

      - name: weather
        description: "Open-Meteo weather data for Belgian locations"
        meta:
          source_url: "https://open-meteo.com/"
          update_frequency: "hourly"